# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
    - name: Cache
      uses: actions/cache@v2.1.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ./node_modules ./package.lock.json
        # An explicit key for restoring and saving the cache
        key: LV{PV<Tp&ZBIsMq1;`U:]*z3!&LGYD@q(Ewfrvg!@bVTjW^v6ZBL@K[N@i+[&v=
